# Generated by Django 3.0.3 on 2020-03-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RomRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
