# Generated by Django 3.0.3 on 2020-03-28 20:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('romrequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='romrequest',
            name='data',
        ),
        migrations.RemoveField(
            model_name='romrequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='romrequest',
            name='tilte',
        ),
        migrations.AddField(
            model_name='romrequest',
            name='attachment',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='c_additions',
            field=models.CharField(choices=[('A', 'New Hire'), ('R', 'Replacement'), ('T', 'Until fulltime is hired'), ('EXT', 'Extension')], default='A', max_length=3),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='c_categories',
            field=models.CharField(choices=[('C', 'Contract'), ('F', 'Full Time Employee')], default='C', max_length=2),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='c_types',
            field=models.CharField(choices=[('S', 'Support'), ('P', 'Project Agreement')], default='S', max_length=2),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='comments',
            field=models.TextField(default='Test'),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='duration_of_contract',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='expected_onboard_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='loction',
            field=models.CharField(choices=[('bangalore', 'Bangalore'), ('coimbatore', 'Coimbatore'), ('chennai', 'Chennai')], default='bangalore', max_length=30),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='manager_id_1',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='manager_id_1_email',
            field=models.CharField(default='email@sample.com', max_length=100),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='manager_id_2',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='manager_id_2_email',
            field=models.CharField(default='email@sample.com', max_length=100),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='no_of_resources_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='project',
            field=models.CharField(choices=[('sample1', 'Sample1'), ('sample', 'Sample')], default='sample', max_length=30),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='romrequest',
            name='request_status',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='requested_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='requested_user_email',
            field=models.CharField(default='email@sample.com', max_length=100),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='sbu',
            field=models.CharField(choices=[('fluid', 'Fluid'), ('power tools and lifting', 'Power Tools and Lifting'), ('club car', 'Club Car'), ('cts', 'CTS')], default='cts', max_length=30),
        ),
        migrations.AddField(
            model_name='romrequest',
            name='skillset_needed',
            field=models.TextField(default='Python'),
        ),
    ]
