# Generated by Django 3.0.3 on 2020-03-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romrequest', '0004_auto_20200328_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stringer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='romrequest',
            name='project',
            field=models.CharField(choices=[('sample', 'Sample'), ('sample1', 'Sample1')], default='sample', max_length=30),
        ),
        migrations.AlterField(
            model_name='romrequest',
            name='sbu',
            field=models.CharField(choices=[('cts', 'CTS'), ('club car', 'Club Car'), ('power tools and lifting', 'Power Tools and Lifting'), ('fluid', 'Fluid')], default='cts', max_length=30),
        ),
    ]
