# Generated by Django 3.0.3 on 2020-03-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romrequest', '0005_auto_20200330_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webapp',
            old_name='Stringer',
            new_name='pc',
        ),
        migrations.AlterField(
            model_name='romrequest',
            name='loction',
            field=models.CharField(choices=[('coimbatore', 'Coimbatore'), ('bangalore', 'Bangalore'), ('chennai', 'Chennai')], default='bangalore', max_length=30),
        ),
        migrations.AlterField(
            model_name='romrequest',
            name='project',
            field=models.CharField(choices=[('sample1', 'Sample1'), ('sample', 'Sample')], default='sample', max_length=30),
        ),
        migrations.AlterField(
            model_name='romrequest',
            name='sbu',
            field=models.CharField(choices=[('club car', 'Club Car'), ('power tools and lifting', 'Power Tools and Lifting'), ('fluid', 'Fluid'), ('cts', 'CTS')], default='cts', max_length=30),
        ),
    ]
